import { ConfigData, SensorConfig } from '@/types/config';
import { SPI_TOUCH_PINS } from './devicePresets';

export const createEmptySensors = (): SensorConfig[] => [
  { id: 'r1c1', type: 'text', entity: '', label: 'Unconfigured', icon: '\\ue8b6', iconColor: '0x888888', enabled: false },
  { id: 'r1c2', type: 'text', entity: '', label: 'Unconfigured', icon: '\\ue8b6', iconColor: '0x888888', enabled: false },
  { id: 'r2c1', type: 'text', entity: '', label: 'Unconfigured', icon: '\\ue8b6', iconColor: '0x888888', enabled: false },
  { id: 'r2c2', type: 'text', entity: '', label: 'Unconfigured', icon: '\\ue8b6', iconColor: '0x888888', enabled: false },
  { id: 'r3c1', type: 'text', entity: '', label: 'Unconfigured', icon: '\\ue8b6', iconColor: '0x888888', enabled: false },
  { id: 'r3c2', type: 'text', entity: '', label: 'Unconfigured', icon: '\\ue8b6', iconColor: '0x888888', enabled: false },
  { id: 'r4c1', type: 'text', entity: '', label: 'Unconfigured', icon: '\\ue8b6', iconColor: '0x888888', enabled: false },
  { id: 'r4c2', type: 'text', entity: '', label: 'Unconfigured', icon: '\\ue8b6', iconColor: '0x888888', enabled: false },
];

const defaultSensors: SensorConfig[] = [
  {
    id: 'r1c1',
    type: 'sensor',
    entity: 'sensor.whole_home_energy_usage',
    label: 'Energy',
    icon: '\\uea0b',
    iconColor: '0xFFA500',
    format: '%.0fW',
    thresholds: [
      { value: '5000', color: '0xFF0000' },
      { value: '3000', color: '0xFFA500' },
      { value: '1000', color: '0x32CD32' },
    ],
  },
  {
    id: 'r1c2',
    type: 'binary',
    entity: 'binary_sensor.front_door_sensor_contact',
    label: 'Front Door',
    stateOn: 'Open',
    stateOff: 'Closed',
    iconOn: '\\ueffc',
    iconOff: '\\ueffc',
    colorOn: '0xFF0000',
    colorOff: '0x32CD32',
  },
  {
    id: 'r2c1',
    type: 'sensor',
    entity: 'sensor.office_presence_one_temperature',
    label: 'Office',
    icon: '\\ue1ff',
    iconColor: '0x00BFFF',
    format: '%.1f°C',
    thresholds: [
      { value: '30', color: '0xFF0000' },
      { value: '25', color: '0xFFA500' },
      { value: '15', color: '0x32CD32' },
    ],
  },
  {
    id: 'r2c2',
    type: 'switch',
    entity: 'switch.zigbee2mqtt_bridge_permit_join',
    label: 'Z2M Join',
    stateOn: 'On',
    stateOff: 'Off',
    iconOn: '\\ue8ac',
    iconOff: '\\ue8ac',
    colorOn: '0x4CAF50',
    colorOff: '0x888888',
  },
  {
    id: 'r3c1',
    type: 'binary',
    entity: 'binary_sensor.garden_pano_person_occupancy',
    label: 'Garden',
    stateOn: 'Detected',
    stateOff: 'Clear',
    iconOn: '\\ue7fd',
    iconOff: '\\ue7fd',
    colorOn: '0xFF0000',
    colorOff: '0x32CD32',
  },
  {
    id: 'r3c2',
    type: 'light',
    entity: 'light.kitchen_downlights',
    label: 'Kitchen',
    stateOn: 'On',
    stateOff: 'Off',
    iconOn: '\\ue0f0',
    iconOff: '\\ue0f0',
    colorOn: '0xFFE082',
    colorOff: '0x888888',
  },
  {
    id: 'r4c1',
    type: 'sensor',
    entity: 'sensor.downstairs_hallway_humidity',
    label: 'Humidity',
    icon: '\\ueb58',
    iconColor: '0x00BFFF',
    format: '%.0f%%',
    thresholds: [
      { value: '80', color: '0xFF0000' },
      { value: '60', color: '0xFFA500' },
      { value: '30', color: '0x32CD32' },
    ],
  },
  {
    id: 'r4c2',
    type: 'binary',
    entity: 'binary_sensor.kitchen_entrance_motion_occupancy',
    label: 'Kitchen',
    stateOn: 'Detected',
    stateOff: 'Clear',
    iconOn: '\\uec10',
    iconOff: '\\uec10',
    colorOn: '0xFF0000',
    colorOff: '0x32CD32',
  },
];

export const defaultConfig: ConfigData = {
  deviceName: 'hamon',
  friendlyName: 'HAMon',
  hideClock: false,
  displaySwapXy: false,
  displayInvertColors: false,
  displayColorOrder: 'RGB',
  deviceVariant: 'spi_touch',
  devicePins: { ...SPI_TOUCH_PINS },
  sensors: defaultSensors,
  screens: [
    {
      id: 's1',
      name: 'Screen 1',
      backgroundColor: '#0f1419',
      fontColor: '#ffffff',
      sensors: defaultSensors,
    },
    {
      id: 's2',
      name: 'Screen 2',
      backgroundColor: '#0f1419',
      fontColor: '#ffffff',
      sensors: createEmptySensors(),
    },
    {
      id: 's3',
      name: 'Screen 3',
      backgroundColor: '#0f1419',
      fontColor: '#ffffff',
      sensors: createEmptySensors(),
    },
  ],
};
