#!/usr/bin/env node
/**
 * Fetches Material Design Icons and Material Symbols codepoint files from
 * github.com/google/material-design-icons and generates lib/icons.generated.ts
 * so all icons from both sets are available without manual listing.
 */

const MDI_CODEPOINTS_URL =
  "https://raw.githubusercontent.com/google/material-design-icons/master/font/MaterialIcons-Regular.codepoints";
const SYMBOLS_CODEPOINTS_URL =
  "https://raw.githubusercontent.com/google/material-design-icons/master/variablefont/MaterialSymbolsOutlined%5BFILL%2CGRAD%2Copsz%2Cwght%5D.codepoints";

/** Parse "name hex" lines; return Map(name -> hex). */
function parseCodepoints(text) {
  const map = new Map();
  for (const line of text.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed) continue;
    const space = trimmed.indexOf(" ");
    if (space === -1) continue;
    const name = trimmed.slice(0, space).trim();
    const hex = trimmed.slice(space + 1).trim().toLowerCase();
    if (name && /^[0-9a-f]+$/.test(hex)) map.set(name, hex);
  }
  return map;
}

/** Derive display name from ligature (e.g. "power_settings_new" -> "Power Settings New"). */
function ligatureToDisplayName(ligature) {
  return ligature
    .split("_")
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase())
    .join(" ");
}

/** Simple category from icon name (prefix/keyword). */
const CATEGORY_RULES = [
  [/^(bolt|flash|power|electric|battery|solar|ev_)/i, "Energy"],
  [/^(door|window|garage|blinds|fence|sensor_door|sensor_window|meeting_room)/i, "Doors"],
  [/^(device_thermostat|thermostat|air|ac_unit|wb_|cloud|grain|thunderstorm|snowing|weather)/i, "Climate"],
  [/^(light|lightbulb|brightness|dark_mode|light_mode|fluorescent|tungsten)/i, "Lights"],
  [/^(water|opacity|leak|shower|hot_tub|humidity)/i, "Water"],
  [/^(lock|security|alarm|alert|notification|camera|shield|visibility|emergency|motion)/i, "Security"],
  [/^(person|group|directions_walk|directions_car|sensor_occupied|hotel|pets|child_)/i, "People"],
  [/^(kitchen|laundry|microwave|coffee|fireplace|cast|live_tv|speaker|music|volume|radio)/i, "Appliances"],
  [/^(wifi|bluetooth|router|signal|network)/i, "Network"],
  [/^(home|bedroom|living|bathroom|dining|weekend|chair|child_care)/i, "Rooms"],
  [/^(eco|grass|park|pool|spa|local_fire_department)/i, "Outdoor"],
  [/^(check|close|settings|speed|schedule|info|error|warning|check_circle)/i, "Status"],
  [/^(call|email|handyman|science|explore|gps)/i, "Misc"],
];

function getCategory(ligature) {
  for (const [pattern, cat] of CATEGORY_RULES) {
    if (pattern.test(ligature)) return cat;
  }
  return "Other";
}

async function fetchText(url) {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`Fetch failed ${url}: ${res.status}`);
  return res.text();
}

function escapeTsString(s) {
  return s.replace(/\\/g, "\\\\").replace(/'/g, "\\'");
}

async function main() {
  console.log("Fetching Material Icons codepoints...");
  const mdiText = await fetchText(MDI_CODEPOINTS_URL);
  console.log("Fetching Material Symbols codepoints...");
  const symText = await fetchText(SYMBOLS_CODEPOINTS_URL);

  const nameToHexMdi = parseCodepoints(mdiText);
  const nameToHexSym = parseCodepoints(symText);

  const hexToNameMdi = new Map();
  for (const [name, hex] of nameToHexMdi) hexToNameMdi.set(hex, name);
  const hexToNameSym = new Map();
  for (const [name, hex] of nameToHexSym) hexToNameSym.set(hex, name);

  const allNames = new Set([...nameToHexMdi.keys(), ...nameToHexSym.keys()]);
  const sortedNames = [...allNames].sort((a, b) => a.localeCompare(b));

  const commonIcons = [];
  for (const ligature of sortedNames) {
    const hexMdi = nameToHexMdi.get(ligature);
    const hexSym = nameToHexSym.get(ligature);
    if (!hexMdi && !hexSym) continue;
    // Double backslash so generated .ts contains '\\uea0b' (literal backslash-u for config)
    const codeMdi = hexMdi ? `\\\\u${hexMdi}` : "";
    const codeSym = hexSym ? `\\\\u${hexSym}` : "";
    const name = ligatureToDisplayName(ligature);
    const category = getCategory(ligature);
    commonIcons.push({ name, ligature, category, codeMdi, codeSymbols: codeSym });
  }

  const fs = await import("fs");
  const path = await import("path");
  const outputPath = path.join(process.cwd(), "lib", "icons.generated.ts");

  const hexToNameMdiObj = Object.fromEntries([...hexToNameMdi.entries()]);
  const hexToNameSymObj = Object.fromEntries([...hexToNameSym.entries()]);

  const gen = `// AUTO-GENERATED by scripts/generate-icons.mjs - do not edit manually.
// Run: npm run generate:icons

/** Material Design Icons: hex codepoint -> ligature name */
export const HEX_TO_NAME_MDI: Record<string, string> = ${JSON.stringify(hexToNameMdiObj, null, 0).replace(/"/g, "'")};

/** Material Symbols: hex codepoint -> ligature name */
export const HEX_TO_NAME_SYMBOLS: Record<string, string> = ${JSON.stringify(hexToNameSymObj, null, 0).replace(/"/g, "'")};

export interface GeneratedIcon {
  name: string;
  ligature: string;
  category: string;
  codeMdi: string;
  codeSymbols: string;
}

export const COMMON_ICONS: GeneratedIcon[] = [
${commonIcons
  .map(
    (i) =>
      `  { name: ${JSON.stringify(i.name)}, ligature: ${JSON.stringify(i.ligature)}, category: ${JSON.stringify(i.category)}, codeMdi: '${i.codeMdi}', codeSymbols: '${i.codeSymbols}' }`
  )
  .join(",\n")}
];
`;

  fs.writeFileSync(outputPath, gen, "utf8");
  console.log(`Wrote ${outputPath} (${commonIcons.length} icons)`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
